### ISSUE TITLE
The format of the dataset

### ISSUE THREAD

**Issue by ZhouHnag** [ZEKAICHEN/GTA#3]
Hello, Zekai.
Thanks for  your brilliant work.

I have some problem when reproducing the work when using SMAP/MSL dataset, can you share the original data when training the network. Thanks a lot!

**Comment by Kiwamm** [comment]
> Hello, Zekai. Thanks for your brilliant work.
> 
> I have some problem when reproducing the work when using SMAP/MSL dataset, can you share the original data when training the network. Thanks a lot!

Hello have you reproducted this work
